### ISSUE TITLE
Add Documentation about Using the Server

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/osm-tileset-chef-repo#2]
The data imports successfully according to the instructions. However, we don't have anything telling the user what to do next. i.e. how do you know the server is running and the data made it successfully into the database. Is there a web UI or something to look at what you've created? What else needs to be done so that it's ready for the tilebundler?

**Comment by mooreja** [comment]
README was updated with information to test and troubleshoot the server.
