### ISSUE TITLE
Zoom Level 19+ not available

### ISSUE THREAD

**Issue by BirdSamuel** [ROGUE-JCTD/osm-tileset-chef-repo#5]
When trying to access this URL: http://[LocationOfVM]/osm_tiles/19/135031/241540.png, I get a 404 Not Found. This is even though I have all of Central America vector data. 

This particular tile should be in Tegucigalpa. Where zoom_level 18 does actually work for this tile.

**Comment by mooreja** [comment]
Mapnik default levels are 0 - 18.  To change the cached zoom levels edit /usr/local/etc/renderd.conf and change MAXZOOM level to the level you want to cache.  You will also need to uncomment the line.

Restart the renderd and apache2 service and the system will be set with the new zoom levels.
